name: Apple Certificate Action
description: Installing an Apple certificate on macOS runners for Xcode development
author: Nicholas Wong
branding:
  icon: anchor
  color: orange
inputs:
  profile-base64:
    description: The Apple provisioning profile which is base64 encoded
    required: false
  profile-file:
    description: Path to the Apple provisioning profile
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      if: ${{ inputs.profile-file != null }}
      run: cp ${{ inputs.profile-file != null }} $RUNNER_TEMP/profile.mobileprovision
    - shell: bash
      if: ${{ inputs.profile != null }}
      run: echo -n ${{ inputs.profile-base64 }} | base64 --decode -o $RUNNER_TEMP/profile.mobileprovision
    - shell: bash
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $RUNNER_TEMP/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles